apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: toursample
  name: toursample
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: toursample:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-webserver31-tomcat8-openshift:latest
        namespace: openshift
    type: Source
